import os
import subprocess
import sys
from datetime import datetime, timezone

from sqlalchemy.orm import Session
from sqlalchemy import select

from analytics.persistence.database import create_database_engine
from analytics.config import load_database_config_from_env
from analytics.persistence.models import MarineObservation, RiskResult, SamplingLocation
from analytics.persistence.marine_repository import MarineObservationRepository
from analytics.persistence.repository import RiskRepository
from analytics.scoring.risk_engine import score_risk_record
from analytics.scoring.models import RiskScoringInput
from analytics.scoring.models import RiskScoringInput

def run_typescript_ingestion():
    # Use npx tsx to run the TypeScript ingestion script
    script_path = os.path.join("backend", "marine", "liveMarineIngestion.ts")
    print("Running TypeScript Open-Meteo extraction...")
    
    db_config = load_database_config_from_env()
    env = os.environ.copy()
    env["MATSYAMITRA_DATABASE_URL"] = db_config.database_url
    
    result = subprocess.run(["npx", "tsx", script_path], capture_output=True, text=True, cwd=os.getcwd(), shell=True, env=env)
    if result.returncode != 0:
        print("TypeScript extraction failed:")
        print(result.stdout)
        print(result.stderr)
        raise RuntimeError(f"TypeScript extraction failed with code {result.returncode}")
    
    print(result.stdout)

def main():
    run_typescript_ingestion()

    engine = create_database_engine()
    with Session(engine) as session:
        marine_repo = MarineObservationRepository(session)
        risk_repo = RiskRepository(session)
        
        # 1. Backfill sampling location IDs
        backfilled_count = marine_repo.backfill_sampling_location_ids()
        print(f"Backfilled sampling_location_id for {backfilled_count} marine observations.")
        
        # 2. Get the latest observations per canonical location
        observations = marine_repo.get_latest_unscored_observations("open-meteo")
        print(f"Found {len(observations)} latest marine observations for scoring.")
        
        # 3. Score and persist
        now = datetime.now(tz=timezone.utc)
        
        inserted_results = 0
        
        for obs in observations:
            # Calculate actual data_age_hours
            if obs.observation_timestamp.tzinfo is None:
                # If naive for some reason, assume UTC
                obs_time = obs.observation_timestamp.replace(tzinfo=timezone.utc)
            else:
                obs_time = obs.observation_timestamp
                
            age_hours = (now - obs_time).total_seconds() / 3600.0
            
            scoring_input = RiskScoringInput(
                wind_speed=obs.wind_speed,
                wave_height=obs.wave_height,
                observation_timestamp=obs_time,
                sampling_location_id=obs.sampling_location_id,
                marine_observation_id=obs.marine_observation_id,
                data_age_hours=max(0.0, age_hours),
                source="open-meteo"
            )
            
            scored_result = score_risk_record(scoring_input)
            
            inserted = risk_repo.insert_risk_result(scored_result)
            inserted_results += inserted
            
        session.commit()
        
        print(f"Successfully generated and inserted {inserted_results} NEW hourly risk results.")
        
        # Live PostgreSQL Verification Report
        all_marine = session.scalars(select(MarineObservation).where(MarineObservation.source == "open-meteo")).all()
        all_risk = session.scalars(select(RiskResult).where(RiskResult.source == "open-meteo")).all()
        
        print("\n--- LIVE POSTGRESQL VERIFICATION REPORT ---")
        
        # marine_observations stats
        print("\nmarine_observations:")
        print(f"- total rows: {len(all_marine)}")
        print(f"- distinct locations: {len(set(m.location_id for m in all_marine))}")
        print(f"- valid wind count: {sum(1 for m in all_marine if m.wind_speed is not None)}")
        print(f"- valid wave count: {sum(1 for m in all_marine if m.wave_height is not None)}")
        timestamps = [m.observation_timestamp for m in all_marine]
        print(f"- earliest timestamp: {min(timestamps) if timestamps else 'N/A'}")
        print(f"- latest timestamp: {max(timestamps) if timestamps else 'N/A'}")
        print(f"- source values: {list(set(m.source for m in all_marine))}")
        
        # risk_results stats
        print("\nrisk_results:")
        print(f"- total rows generated by this test: {inserted_results}")
        print(f"- distinct locations: {len(set(r.sampling_location_id for r in all_risk))}")
        r_timestamps = [r.observation_timestamp for r in all_risk]
        print(f"- earliest timestamp: {min(r_timestamps) if r_timestamps else 'N/A'}")
        print(f"- latest timestamp: {max(r_timestamps) if r_timestamps else 'N/A'}")
        print(f"- valid risk score count: {sum(1 for r in all_risk if r.risk_score is not None)}")
        scores = [r.risk_score for r in all_risk if r.risk_score is not None]
        print(f"- risk score min/max: {min(scores):.2f}/{max(scores):.2f}" if scores else "- risk score min/max: N/A")
        confidences = [r.confidence_score for r in all_risk]
        print(f"- confidence min/max: {min(confidences):.2f}/{max(confidences):.2f}" if confidences else "- confidence min/max: N/A")
        print(f"- risk categories: {list(set(r.risk_category for r in all_risk))}")
        
        # Sample records
        print("\nSample records:")
        samples = []
        # Let's get the 5 latest risk results
        for r in sorted(all_risk, key=lambda x: x.id, reverse=True)[:5]:
            # find corresponding marine obs
            m_obs = session.get(MarineObservation, r.marine_observation_id)
            samples.append({
                "location_id": m_obs.location_id if m_obs else "UNKNOWN",
                "canonical_latitude": m_obs.latitude if m_obs else 0,
                "canonical_longitude": m_obs.longitude if m_obs else 0,
                "observation_timestamp": r.observation_timestamp.isoformat(),
                "wind_speed": r.wind_speed,
                "wave_height": r.wave_height,
                "risk_score": r.risk_score,
                "risk_category": r.risk_category,
                "confidence_score": r.confidence_score,
                "source": r.source
            })
            
        import json
        print(json.dumps(samples, indent=2))

if __name__ == "__main__":
    main()
